### ISSUE TITLE
Empty array not been included in the serialized json

### ISSUE THREAD

**Issue by rtanizawa-salsa** [svix/svix-webhooks#1151] opened 2023-12-22 13:33 UTC
## Bug Report
Message containing a field with an empty array is not included in the json payload when serializing a HashMap

### Version
1.15.0

### Platform
Koltin

### Description

Example:
```
// Payload
val dataMap = mapOf(
    "id" to "123",
    "name" to "My name",
    "workerIds" to arrayListOf<String>()
)
val payload = mapOf("data" to mapOf("attributes" to dataMap))

// Call Svix
val messageOut = svix.message.create(
    myAppId,
    MessageIn(
        eventType = myEventType,
        eventId = myEventId,
        payload = payload
    ),
    PostOptions()
)
```

Currently the payload message goes as:
```
{
  "data": {
    "attributes": {
      "id": "123",
      "name": "My name"
    }
  }
}
```

The expected message should be:
```
{
  "data": {
    "attributes": {
      "id": "123",
      "name": "My name",
      "workerIds": []
    }
  }
}
```

**Comment by svix-james** [comment] 2023-12-27 20:48
@rtanizawa-salsa I'm not able to reproduce this issue in my testing. Is it possible you have some global settings configured for serialization that might be causing this? 

If possible, can you please post a working, reproducible example?

**Comment by svix-james** [comment] 2024-08-21 15:53
Closing for now. Please feel free to reopen if you have a repro.

**Closed by svix-james** 2024-08-21 15:53 UTC
Labels: lib/kotlin
