### ISSUE TITLE
Models and apis folder missing from rust client

### ISSUE THREAD

**Issue by imabdulbasit** [svix/svix-webhooks#775] opened 2023-01-20 16:49 UTC
### Version
0.1.0

### Platform
linux_x86_64

### Description

![Screenshot from 2023-01-20 21-46-16](https://user-images.githubusercontent.com/45506001/213755914-a77ca677-79bf-4d12-a2c6-541bb4824a0a.png)

**Comment by tasn** [comment] 2023-01-20 19:41
Thanks for the report, but it's not actually missing, you're expected to generate it locally when working on it (see the CI for how to do it), we don't want to commit generated files to git!

I'm closing this ticket because it works as intended, but do let me know if I misunderstood something and we'll reopen it.

Thanks!

**Closed by tasn** 2023-01-20 19:41 UTC
